### ISSUE TITLE
How to use the 'run request' command in VS Code？？

### ISSUE THREAD

**Issue by ShenGuangYang** [usebruno/bruno-ide-extensions#14]
![image](https://github.com/usebruno/bruno-ide-extensions/assets/18436796/1ae6e163-80d4-4d1b-b21a-65b1c295447d)

How to use the 'run request' command in VS Code？？

**Comment by marfranke** [comment]
- This request looks like the old syntax.
- Bruno Panel is still broken (known issue...)

But to answer your question:

1. Within a .bru file, open the command palette (Default settings: **Ctrl + Shift + P**, or via context menu)
2. Select **Bruno: Run Request**
