### ISSUE TITLE
VSCode Embedded Requests

### ISSUE THREAD

**Issue by cgatian** [usebruno/bruno-ide-extensions#6]
It would be nice if the VS Code extension could issue requests right from the IDE without the desktop app, similar to Thunder Client. 💯

**Comment by helloanoop** [comment]
Definitely. You can checkout our [roadmap](https://github.com/usebruno/bruno/discussions/384)

We already have support for syntax as well as running requests, but its not actively maintained.
You can checkout the [demo](https://www.youtube.com/watch?v=yVF13_9S6ng&t=138s)

After we v1, we will spend more efforts on enhancing and maintaining the VSCode extension.

**Comment by cgatian** [comment]
Ahh didn't know there was some basic requests already there I thought it was just syntax highlight.
Getting this error.

![image](https://github.com/usebruno/bruno-ide-extensions/assets/1752170/53b29a22-986c-49b5-883b-905b97731bdc)

**Comment by cgatian** [comment]
Ahh related to #5

**Comment by kirstyannepollock** [comment]
ah ... I thought this was already built in like Flashpost or Thunderclient! This explains why I cant see what I expect!
